  - name: Installing Chrony
    ansible.builtin.dnf:
      name:
        - chrony
      state: present
      #use_backend: yum5

  - name: Start Chronyd Service
    ansible.builtin.systemd:
      name: chronyd
      state: started
      enabled: yes

  - name: Set timezone to Europe/Moscow
    community.general.timezone:
      name: Europe/Moscow
    notify: Restart Chronyd