# code: language=ansible
- name: install targetcli, create lun
  hosts: iscsi_srv
  #gather_facts: false
  become: yes
  vars :
    ansible_ssh_private_key_file: /home/alexey/.ssh/akopalev-dip
  roles:
  - targetcli