- name: Install Chrony
  hosts: 
    - iscsi_srv
    #- pcs_hosts
  gather_facts: false
  become: true
  #vars :
  #  ansible_ssh_private_key_file: /home/alexey/.ssh/akopalev-dip
  roles:
    - chrony