###-----Create bastion host----------------###

- name: Clone bastion VM
  community.general.proxmox_kvm:
    node: "{{ node }}"
    name: "{{ bast_host.name }}"
    newid: "{{ bast_host.vmid }}"
    api_host: "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user: "{{ api_user }}"
    clone: "{{ clone_vm }}"
    full: yes

- name: Set IP addresses bastion VM
  ansible.builtin.command: "qm set {{ bast_host.vmid }}  --ipconfig0 ip={{ bast_host.ipaddress }},gw=10.6.6.1"

- name: Copy SSH key bastion VM
  ansible.builtin.command: "qm set {{ bast_host.vmid }} --sshkey {{ key_name }}"
  args:
    chdir: /tmp

- name: Update bastion VM
  community.general.proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user:     "{{ api_user }}"
    cores:        "{{ bast_host.cores }}"
    sockets:      "{{ bast_host.sockets }}"
    memory:       "{{ bast_host.memory }}"
    update:       yes
    vmid:         "{{ bast_host.vmid }}"
    node:         "{{ node }}"
    name:         "{{ bast_host.name }}"
    
- name: Start bastion VM
  community.general.proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user:     "{{ api_user }}"
    vmid:         "{{ bast_host.vmid }}"
    node:         "{{ node }}"
    state:        started

###-----Create nginx_srv----------------###

- name: Clone VMs
  community.general.proxmox_kvm:
    node: "{{ node }}"
    name: "{{ item.value.name }}"
    newid: "{{ item.value.vmid }}"
    api_host: "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user: "{{ api_user }}"
    clone: "{{ clone_vm }}"
    full: yes
  loop: "{{ lookup('dict', vms) }}"

- name: Copy userconfig.yaml
  ansible.builtin.template:
      src: userconfig.yaml.j2
      dest: /mnt/pve/ssd_1tb/snippets/userconfig_{{ item.value.name }}.yaml
  loop: "{{ lookup('dict', vms) }}"

- name: set hostname and hosts
  ansible.builtin.command: 'qm set {{ item.value.vmid }} --cicustom "user=ssd_1tb:snippets/userconfig_{{ item.value.name }}.yaml"'
  loop: "{{ lookup('dict', vms) }}"

- name: Set IP addresses
  ansible.builtin.command: "qm set {{ item.value.vmid }}  --ipconfig0 ip={{ item.value.ipaddress }}/{{ item.value.mask }},gw=10.6.7.10"
  loop: "{{ lookup('dict', vms) }}"

# - name: Copy SSH key
#   ansible.builtin.command: "qm set {{ item.value.vmid }} --sshkey {{ key_name }}"
#   args:
#     chdir: /tmp
#   loop: "{{ lookup('dict', vms) }}"

- name: Update VMs
  community.general.proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user:     "{{ api_user }}"
    cores:        "{{ item.value.cores }}"
    sockets:      "{{ item.value.sockets }}"
    memory:       "{{ item.value.memory }}"
    net:
        net0: virtio,bridge=vmbr1
    update: true
    update_unsafe: true
    vmid:         "{{ item.value.vmid }}"
    node:         "{{ node }}"
    name:         "{{ item.value.name }}"
  loop: "{{ lookup('dict', vms) }}"

- name: Start VMs
  community.general.proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_user:     "{{ api_user }}"
    vmid:         "{{ item.value.vmid }}"
    node:         "{{ node }}"
    state:        started
  loop: "{{ lookup('dict', vms) }}"

- name: Wait a little
  ansible.builtin.pause:
    seconds: 30