# FluentBit Settings
log_out_host: 10.6.7.11
log_out_port: 9200
log_root: /var/log
fluentbit_custom_parsers:
  - Name: syslog-custom
    Format: regex
    Regex: '/^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/'
    Time_Key: time
    Time_Format: "%b %d %H:%M:%S"
    Time_Keep: "On"
    Time_Offset: "+0300"
  - Name: json-custom
    Format: json
    Time_Key: time
    Time_Format: "%Y-%m-%dT%H:%M:%S.%L"
    Time_Keep: "On"
    Time_Offset: "+0300"
    Decode_Field_As: |4
        escaped_utf8 message do_next
            Decode_Field_As json message
  - Name: nginx-custom
    Format: regex
    Regex: '^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<client_ip>[^\"]*)")'
    Time_Key: time
    Time_Format: "%d/%b/%Y:%H:%M:%S %z"

fluentbit_inputs:
  - Name: syslog
    Tag:   syslog
    Parser: syslog-custom
    Listen: 127.0.0.1
    Port: 5140
    Mode: tcp
    Buffer_Chunk_Size: 1M
    Buffer_Max_Size: 16M
  - Name: tail
    Tag: nginx.access
    path: /var/log/nginx/access.log
    parser:  nginx-custom
  - Name:  tail
    Tag:   nginx.error
    path:  /var/log/nginx/error.log
fluentbit_filters:
  - Name: parser
    Parser: json-custom
    Match: "*"
    Key_Name: message
    Reserve_Data: On
    Preserve_Key: Off

fluentbit_outputs:
  - Name: opensearch
    #Match: "*"
    Match: syslog
    Host: "{{ log_out_host }}"
    Port: "{{ log_out_port }}"
    HTTP_User: fluentbit
    HTTP_Passwd: "{{ fluentbit_password }}"
    Tls: "On"
    Tls.verify: "Off"
    Index: syslog
    Logstash_Format: "on"
    Logstash_Prefix: syslog
    Suppress_Type_Name: "On"
  - Name:  opensearch
    Match: nginx.access
    Host: 10.6.7.11
    port: 9200
    HTTP_User: fluentbit
    HTTP_Passwd: "{{ fluentbit_password }}"
    Tls: True
    Tls.verify: False
    Index: fbit-nginx-access
    Logstash_Format: "on"
    Logstash_Prefix: fbit-nginx-access
    Suppress_Type_Name: "On"
  - Name:  opensearch
    Match: nginx.error
    Host: 10.6.7.11
    port: 9200
    HTTP_User: fluentbit
    HTTP_Passwd: "{{ fluentbit_password }}"
    Tls: "True"
    Tls.verify: "False"
    Index: fbit-nginx-error
    Logstash_Format: "on"
    Logstash_Prefix: fbit-nginx-error
    Suppress_Type_Name: "On"