- name: Install Chrony
  hosts: 
    - bast-host
    - haproxy_hosts
    - db_hosts
    - backend_hosts
    - iscsi_srv
    - proxysql_hosts
  gather_facts: false
  become: true
  vars :
    ansible_ssh_private_key_file: /home/alexey/.ssh/akopalev-dip
  roles:
    - chrony