# code: language=ansible
- name: install iscsi-client
  hosts: backend_hosts
  #gather_facts: false
  become: yes
  vars :
    ansible_ssh_private_key_file: /home/alexey/.ssh/akopalev-dip
  roles:
  - iscsi-client