api_host: pve-fortest
api_user: otus@pve-fortest
api_token_id: ansible
api_token_secret: "{{ api_token_secret }}"
node: pve-fortest
clone_vm: AlmaLinux-9-GenericCloud-amd64
key_name: akopalev-dip.pub
pause_timer: 60

vms:
  bast_host:
    name: bast-host #.roter.lan
    domainname: roter.lan
    ipaddress: 10.6.6.11
    mask: 24
    gateway: 10.6.6.1
    bridge: vmbr0
    vmid: 101
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  iscsi-srv1:
    name: iscsi-srv1
    domainname: otushl.local
    ipaddress: 10.6.7.3
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 103
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  nginx-srv1:
    name: nginx-srv1 
    domainname: otushl.local
    ipaddress: 10.6.7.4
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 104
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  nginx-srv2:
    name: nginx-srv2 
    domainname: otushl.local
    ipaddress: 10.6.7.5
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 105
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  db_srv1:
    name: db-srv1
    domainname: otushl.local
    ipaddress: 10.6.7.6
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 106
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  backend1:
    name: backend1
    domainname: otushl.local
    ipaddress: 10.6.7.9
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 109
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  backend2:
    name: backend2
    domainname: otushl.local
    ipaddress: 10.6.7.10
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 110
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  consul-01:
    name: consul-01
    domainname: otushl.local
    ipaddress: 10.6.7.18
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 118
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  consul-02:
    name: consul-02
    domainname: otushl.local
    ipaddress: 10.6.7.19
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 119
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  consul-03:
    name: consul-03
    domainname: otushl.local
    ipaddress: 10.6.7.20
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 120
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"