- name: Started VMs
  proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_user:     "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid:         "{{ item.value.vmid }}"
    node:         "{{ node }}"
    state:        started
    force:        true
  loop: "{{ lookup('dict', vms) }}"
