- name: Stopped VMs
  proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_user:     "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid:         "{{ item.value.vmid }}"
    node:         "{{ node }}"
    state:        stopped
  loop: "{{ lookup('dict', vms) }}"
- name: Remove VMs
  proxmox_kvm:
    api_host:     "{{ api_host }}"
    api_user:     "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid:         "{{ item.value.vmid }}"
    node:         "{{ node }}"
    state:        absent
  loop: "{{ lookup('dict', vms) }}"