- name: Setup Python and pip
  ansible.builtin.apt:
        name: "{{ item }}"
        state: present
  become: true
  loop:
       - python3
       - python3-pip   

- name: Install pip modules
  ansible.builtin.pip:
        name:
          - requests
          - proxmoxer

- name: Copy ssh pub key
  ansible.builtin.copy:
      src: akopalev-dip.pub
      dest: /tmp/akopalev-dip.pub