---
proxysql_admin_user: admin
proxysql_admin_password: admin

proxysql_admin_interface: 127.0.0.1
proxysql_admin_port: 6032

# Force database wipe
proxysql_initial: true

proxysql_mysql_interface: 127.0.0.1

proxysql_mysql_port: 6033

# Query rules
# Format:
# proxysql_mysql_query_rules:
#   - match_pattern: "^SELECT .* FOR UPDATE$"
#     destination_hostgroup: 0
#   - match_pattern: "^SELECT"
#     destination_hostgroup: 1
#
proxysql_mysql_query_rules: []

# Servers
# Format:
# proxysql_mysql_servers:
#   - address: 127.0.0.1
#     port: 3306
#     hostgroup: 0
#   - address: 1.2.3.4
#     port: 3306
#     hostgroup: 1
proxysql_mysql_servers:
  - address: 10.6.7.6
    port: 3306
    hostgroup: 0
  - address: 10.6.7.7
    port: 3306
    hostgroup: 0
  - address: 10.6.7.8
    port: 3306
    hostgroup: 0
# Users
# Format:
# proxysql_mysql_users:
#   - username: foo
#     password: bar
#     default_hostgroup: 0  # default: 0
proxysql_mysql_users: 
  - username: "{{ wp_user }}"
    password: "{{ wp_pass }}"

proxysql_cluster_name: false
proxysql_cluster_password: false

proxysql_mysql_server_version: 8.0.37

proxysql_version: 2.6