---
- name: Hosts | populate inventory into hosts file
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in groups['kafka_servers'] %}
      {{ hostvars[item].ansible_host }} {{ item }}.{{ domain_name }} {{ item }}
      {% endfor %}
    state: present
    create: true
    backup: true
    marker: "# Ansible kafka hosts {mark}"
  #when: populate_inventory_to_hosts_file
