api_host: pve-fortest
api_user: otus@pve-fortest
api_token_id: ansible
api_token_secret: "{{ api_token_secret }}"
node: pve-fortest
clone_vm: AlmaLinux-9-GenericCloud-amd64
key_name: akopalev-dip.pub

vms:
  bast_host:
    name: bast-host #.roter.lan
    domainname: roter.lan
    ipaddress: 10.6.6.11
    mask: 24
    gateway: 10.6.6.1
    bridge: vmbr0
    vmid: 100
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  iscsi-srv1:
    name: iscsi-srv1
    domainname: otushl.local
    ipaddress: 10.6.7.3
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 101
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  nginx_srv1:
    name: haproxy-srv1 #.otushl.local
    domainname: otushl.local
    ipaddress: 10.6.7.4
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 102
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  nginx_srv2:
    name: haproxy-srv2 #.otushl.local
    domainname: otushl.local
    ipaddress: 10.6.7.5
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 103
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  db_srv1:
    name: db-srv1
    domainname: otushl.local
    ipaddress: 10.6.7.6
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 104
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  db_srv2:
    name: db-srv2
    domainname: otushl.local
    ipaddress: 10.6.7.7
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 105
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  db_srv3:
    name: db-srv3
    domainname: otushl.local
    ipaddress: 10.6.7.8
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 106
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  backend1:
    name: backend1
    domainname: otushl.local
    ipaddress: 10.6.7.9
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 107
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
  backend2:
    name: backend2
    domainname: otushl.local
    ipaddress: 10.6.7.10
    mask: 24
    gateway: 10.6.7.1
    bridge: vmbr1
    vmid: 108
    cores: 2
    sockets: 1
    memory: 2048
    disk: 10
    storage: "ssd_1tb"
